apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "composite-key.fullname" . }}
  labels:
{{ include "composite-key.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "composite-key.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/selector: {{ include "composite-key.name" . }}-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "composite-key.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/selector: {{ include "composite-key.name" . }}-backend
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
