{{- if .Values.ingress.enabled -}}
{{- $fullName := include "composite-key.fullname" . -}}
{{- $name := include "composite-key.name" . -}}
{{- $services := .Values.ingress.services -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "composite-key.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- range $httpHost := .Values.ingress.hosts }}
      - host: {{ . }}
        http:
          paths:
      {{- range $service := $services }}
        {{- range $path := .paths }}
            - path: {{ $path }}
              backend:
                serviceName: {{ $name }}-{{ $service.name }}-service
                servicePort: {{ $servicePort }}
      {{- end }}  
    {{- end }}    
  {{- end }}    
{{- end }}
