apiVersion: v1
kind: Service
metadata:
  name: {{ include "composite-key.name" . }}-backend
  labels:
{{ include "composite-key.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "composite-key.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/selector: {{ include "composite-key.name" . }}-backend
